---
title: "Valley Bike Exploratory Analysis"
author: "Nicholas Horton (nhorton@amherst.edu)"
date: "June 28, 2019"
output: 
  html_document:
    fig_height: 3
    fig_width: 5
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
library(mosaic)   
library(leaflet)
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

## Initial data exploration

```{r}
July01 <- readxl::read_excel("VB_Routes_Data_2018_07_1.xlsx", skip = 2) %>%
  janitor::clean_names() %>%
  mutate(date = lubridate::ymd_hms(date))
names(July01)
glimpse(July01)
#tally(~ route_id, data = July01)
tally(~ bike, data = July01)
#tally(~ user_id, data = July01)
```

```{r}
onebike <- filter(July01, bike == 967)
glimpse(onebike)
```

```{r}
oneuser <- filter(July01, user_id == "f517005b-4559-4d10-940b-9f30474c119d")
glimpse(oneuser)
```

```{r}
m <- leaflet(oneuser) %>% 
  addTiles() %>% 
  addMarkers(~longitude, ~latitude, popup = ~ bike)
m
```
```{r}
gf_point(latitude ~ longitude, color = ~ date, data = oneuser)
```

```{r}
m <- leaflet(onebike) %>% 
  addTiles() %>% 
  addMarkers(~longitude, ~latitude, popup = ~ user_id)
m
```{r}
gf_point(longitude ~ latitude, color = ~ date, data = onebike)
```