---
title: "Untitled"
author: ""
date: ""
output: 
  html_document:
    fig_height: 3
    fig_width: 5
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

sample day is sample excel reading in raw data (in valley bikes project reading into VB-)

```{r}
July01 <- readxl::read_excel("../data-raw/VB_Routes_Data_2018_07_1.xlsx", skip = 2) %>%
  janitor::clean_names() %>%
  mutate(date = lubridate::ymd_hms(date))
names(July01)
glimpse(July01)
#max lat: 42.39071, min lat: 42.20164 
#max long: -72.51715, min long: -72.67590
tally(~ route_id, data = July01)
tally(~ bike, data = July01)
#tally(~ user_id, data = July01)
tally(~ route_id+ bike, data=July01)
```

```{r}
July17 <- readxl::read_excel("../data-raw/VB_Routes_Data_2018_07_13.xlsx", skip = 2) %>%
  janitor::clean_names() %>%
  mutate(date = lubridate::ymd_hms(date))
#max lat: 42.39071, min lat: 42.20164 
#max long: -72.51715, min long: -72.67590
```
```{r}
#GATHERING LOCATIONS BY CITY
#SPRINGFIELD
Springfield<-filter(July17, latitude< 42.15)
#EXPLORING BIKES IN SPRINGFIELD
bike1221<- filter(Springfield, bike == "1221")
s <- leaflet(bike1221) %>% 
  addTiles() %>%
  addMarkers(~ longitude, ~ latitude, popup = ~ user_id)
s

bike1322<- filter(Springfield, bike == "1322")
s2 <- leaflet(bike1322) %>% 
  addTiles() %>%
  addMarkers(~ longitude, ~ latitude, popup = ~ user_id)
s2

bike1164<- filter(Springfield, bike == "1164")
s3 <- leaflet(bike1164) %>% 
  addTiles() %>%
  addMarkers(~ longitude, ~ latitude, popup = ~ user_id)
s3

#HOLYOKE
Holyoke<-filter(July17, latitude> 42.15, latitude< 42.25)
#EXPLORING BIKES IN HOLYOKE
bike933<- filter(Holyoke, bike == "933")
h <- leaflet(bike933) %>% 
  addTiles() %>%
  addMarkers(~ longitude, ~ latitude, popup = ~ user_id)
h

bike925<- filter(Holyoke, bike == "925")
h1 <- leaflet(bike925) %>% 
  addTiles() %>%
  addMarkers(~ longitude, ~ latitude, popup = ~ user_id)
h1

bike912<- filter(Holyoke, bike == "912")
h2 <- leaflet(bike912) %>% 
  addTiles() %>%
  addMarkers(~ longitude, ~ latitude, popup = ~ user_id)
h2

bike1244<- filter(Holyoke, bike == "1244")
h3 <- leaflet(bike1244) %>% 
  addTiles() %>%
  addMarkers(~ longitude, ~ latitude, popup = ~ user_id)
h3

bike945<- filter(Holyoke, bike == "945")
h4 <- leaflet(bike945) %>% 
  addTiles() %>%
  addMarkers(~ longitude, ~ latitude, popup = ~ user_id)
h4




```

```{r}
#EXPLORING MAPS
#SPring
bike915 <- filter(July01, bike == "915")
bike923 <- filter(July01, bike == "923")
library(leaflet)
#bike 915
a <- leaflet(bike915) %>% 
  addTiles() %>%
  addMarkers(~ longitude, ~ latitude, popup = ~ user_id)
a
#bike 923
b <- leaflet(bike923) %>% 
  addTiles() %>%
  addMarkers(~ longitude, ~ latitude, popup = ~ user_id)
b
```
group by route ID, grab the first entry, save lat long into data, match the stations to the lat long

